name: Build_verification
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
    
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

#     - name: checkout
#       uses: actions/checkout@v3 #checkout the code

#    - name: Setup Gradle
#      uses: gradle/gradle-build-action@v2

#    - name: build with gradle
#      run: gradle build

#     - name: printing apk
#       run: ls app/build/outputs/apk/debug/app-debug.apk

    - name: Cloning Test Repo
      uses: actions/checkout@v2
      with:
        repository: saumilrewari/test
        path: /Users/runner/work/cicd/cicd/test
        submodules: recursive

    - name: Checking File Exist
      uses: andstor/file-existence-action@v2
      with:
        files: "test/opsis_project, test/opsis_project/requirements.txt, test.apk"
        
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo All files exists!
      
    - name: Install and Run Appium Server
      run: |
        chmod +x test/RunAppiumServer.sh
        sh test/RunAppiumServer.sh

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python3 --version

    - name: Installing Dependencies
      run: pip3 install -r test/opsis_project/requirements.txt

    - name: Turn on Emulator and Run Test 
      uses: ReactiveCircus/android-emulator-runner@v2.27.0
      with:
        api-level: 29
        script: pytest -k="test_pass" -v
